### ISSUE TITLE
LiDAR/Oak Camera Timeout or error

### ISSUE THREAD

**Issue by naman-gupta99** [waveshareteam/ugv_ws#6]
I am trying to run `ros2 launch ugv_slam rtabmap_rgbd.launch.py use_rviz:=true`.

The visualization spawns up and the camera feed gets updated a couple of times and after that the visualization gets stuck and I get the following logs in the terminal.

[logfile.txt](https://github.com/user-attachments/files/19019816/logfile.txt)

I've run the following commands:
```
top
kill -9 <python pid>
cd /home/ws/ugv_ws
./ros2_humble.sh

# In SSH
cd /home/ws/ugv_ws
ros2 launch ugv_slam rtabmap_rgbd.launch.py use_rviz:=true
```

**Comment by DUDULRX** [comment]
![Image](https://github.com/user-attachments/assets/34b8426b-06a5-4d5d-a188-157f3dbbcb13)
Please make sure that the device lidar，oak camera is connected properly

**Comment by naman-gupta99** [comment]
I did check that multiple times and they are connected properly.

Also, it does run for about second where I can see the camera feed and lidar points on the rviz UI.

**Comment by DUDULRX** [comment]
Please make sure that the power supply is sufficient

**Comment by naman-gupta99** [comment]
Are there any steps to check that? 

Also, is there a way to view just the feed from the Oak Camera without running SLAM?

**Comment by DUDULRX** [comment]
first,run `ros2 run ugv_bringup ugv_bringup`,`ros2 topic echo /voltage`

second, `ros2 launch ugv_vision oak_d_lite.launch.py`, `ros2 run rqt_image_view rqt_image_view oak/rgb/image_rect `

**Comment by naman-gupta99** [comment]
Following is the voltage data.
```
root@raspberrypi:/home/ws/ugv_ws# ros2 topic echo /voltage
data: 12.140000343322754
---
data: 12.140000343322754
---
data: 12.140000343322754
---
data: 12.140000343322754
---
data: 12.140000343322754
---
data: 12.140000343322754
---
data: 12.140000343322754
---
data: 12.140000343322754
---
data: 12.140000343322754
---
data: 12.140000343322754
---
data: 12.140000343322754
---
data: 12.140000343322754
---
data: 12.140000343322754
```

**Comment by naman-gupta99** [comment]
Even when I am trying to run the camera I am getting this error. The fan suddenly start running really fast, whenever I run the camera commands and I see 1 image frame and then it gets stuck and I start getting errors like mentioned below

```
root@raspberrypi:/home/ws/ugv_ws# ros2 launch ugv_vision oak_d_lite.launch.py
[INFO] [launch]: All log files can be found below /root/.ros/log/2025-02-28-15-34-06-387504-raspberrypi-1263
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [component_container-1]: process started with pid [1278]
[component_container-1] [INFO] [1740756846.866716831] [oak_container]: Load Library: /opt/ros/humble/lib/librobot_state_publisher_node.so
[component_container-1] [INFO] [1740756846.869862639] [oak_container]: Found class: rclcpp_components::NodeFactoryTemplate<robot_state_publisher::RobotStatePublisher>
[component_container-1] [INFO] [1740756846.869906787] [oak_container]: Instantiate class: rclcpp_components::NodeFactoryTemplate<robot_state_publisher::RobotStatePublisher>
[component_container-1] [INFO] [1740756846.877618260] [oak_state_publisher]: got segment 3d_camera_link
[component_container-1] [INFO] [1740756846.877677278] [oak_state_publisher]: got segment oak
[component_container-1] [INFO] [1740756846.877687334] [oak_state_publisher]: got segment oak_imu_frame
[component_container-1] [INFO] [1740756846.877694853] [oak_state_publisher]: got segment oak_left_camera_frame
[component_container-1] [INFO] [1740756846.877703464] [oak_state_publisher]: got segment oak_left_camera_optical_frame
[component_container-1] [INFO] [1740756846.877712427] [oak_state_publisher]: got segment oak_model_origin
[component_container-1] [INFO] [1740756846.877721556] [oak_state_publisher]: got segment oak_rgb_camera_frame
[component_container-1] [INFO] [1740756846.877729631] [oak_state_publisher]: got segment oak_rgb_camera_optical_frame
[component_container-1] [INFO] [1740756846.877738223] [oak_state_publisher]: got segment oak_right_camera_frame
[component_container-1] [INFO] [1740756846.877746705] [oak_state_publisher]: got segment oak_right_camera_optical_frame
[INFO] [launch_ros.actions.load_composable_nodes]: Loaded node '/oak_state_publisher' in container 'oak_container'
[component_container-1] [INFO] [1740756846.880418122] [oak_container]: Load Library: /opt/ros/humble/lib/libdepthai_ros_driver.so
[component_container-1] [INFO] [1740756846.959823022] [oak_container]: Found class: rclcpp_components::NodeFactoryTemplate<depthai_ros_driver::Camera>
[component_container-1] [INFO] [1740756846.959935837] [oak_container]: Instantiate class: rclcpp_components::NodeFactoryTemplate<depthai_ros_driver::Camera>
[component_container-1] [INFO] [1740756846.966774695] [oak]: No ip/mxid specified, connecting to the next available device.
[component_container-1] [INFO] [1740756849.440662627] [oak]: Camera with MXID: 14442C103141E0D600 and Name: 3.1 connected!
[component_container-1] [INFO] [1740756849.441406260] [oak]: USB SPEED: HIGH
[component_container-1] [INFO] [1740756849.487034055] [oak]: Device type: OAK-D-LITE
[component_container-1] [INFO] [1740756849.488658765] [oak]: Pipeline type: RGBD
[component_container-1] [INFO] [1740756849.682339655] [oak]: Finished setting up pipeline.
[component_container-1] [INFO] [1740756850.163781501] [oak]: Camera ready!
[component_container-1] [INFO] [1740756850.164344800] [oak_container]: Load Library: /opt/ros/humble/lib/librectify.so
[INFO] [launch_ros.actions.load_composable_nodes]: Loaded node '/oak' in container '/oak_container'
[component_container-1] [INFO] [1740756850.166551956] [oak_container]: Found class: rclcpp_components::NodeFactoryTemplate<image_proc::RectifyNode>
[component_container-1] [INFO] [1740756850.166601845] [oak_container]: Instantiate class: rclcpp_components::NodeFactoryTemplate<image_proc::RectifyNode>
[INFO] [launch_ros.actions.load_composable_nodes]: Loaded node '/rectify_color_node' in container 'oak_container'
[component_container-1] [ERROR] [1740756862.928602996] [oak]: No data on logger queue!
[component_container-1] [ERROR] [1740756862.928858812] [oak]: Camera diagnostics error: Communication exception - possible device error/misconfiguration. Original message 'Couldn't read data from stream: 'sys_logger_queue' (X_LINK_ERROR)'
[component_container-1] [ERROR] [1740756863.928596111] [oak]: No data on logger queue!
[component_container-1] [ERROR] [1740756863.928849779] [oak]: Camera diagnostics error: Communication exception - possible device error/misconfiguration. Original message 'Couldn't read data from stream: 'sys_logger_queue' (X_LINK_ERROR)'
[component_container-1] [ERROR] [1740756864.928586079] [oak]: No data on logger queue!
[component_container-1] [ERROR] [1740756864.928810117] [oak]: Camera diagnostics error: Communication exception - possible device error/misconfiguration. Original message 'Couldn't read data from stream: 'sys_logger_queue' (X_LINK_ERROR)'
[component_container-1] [ERROR] [1740756865.928570862] [oak]: No data on logger queue!
[component_container-1] [ERROR] [1740756865.928806474] [oak]: Camera diagnostics error: Communication exception - possible device error/misconfiguration. Original message 'Couldn't read data from stream: 'sys_logger_queue' (X_LINK_ERROR)'

```

**Comment by DUDULRX** [comment]
[oak](https://github.com/luxonis/depthai-ros/issues/575)

**Comment by naman-gupta99** [comment]
How can we fix this then?
I have the following info in the diagnostics topic. I don't think there's anything useful here.
```
header:
  stamp:
    sec: 1740806521
    nanosec: 556034201
  frame_id: ''
status:
- level: "\x02"
  name: 'rtabmap: Sync status'
  message: No events recorded.; No data since last update.
  hardware_id: none
  values:
  - key: Events in window
    value: '0'
  - key: Events since startup
    value: '0'
  - key: Duration of window (s)
    value: '4.999979'
  - key: Actual frequency (Hz)
    value: '0.000000'
  - key: Target frequency (Hz)
    value: '0.000000'
  - key: Maximum acceptable frequency (Hz)
    value: '0.000000'
  - key: 'Earliest timestamp delay:'
    value: '0.000000'
  - key: 'Latest timestamp delay:'
    value: '0.000000'
  - key: 'Earliest acceptable timestamp delay:'
    value: '-1.000000'
  - key: 'Latest acceptable timestamp delay:'
    value: '5.000000'
  - key: 'Late diagnostic update count:'
    value: '0'
  - key: 'Early diagnostic update count:'
    value: '0'
  - key: 'Zero seen diagnostic update count:'
    value: '0'
---
header:
  stamp:
    sec: 1740806521
    nanosec: 643101486
  frame_id: ''
status:
- level: "\x02"
  name: 'rtabmap_viz: Sync status'
  message: No events recorded.; No data since last update.
  hardware_id: none
  values:
  - key: Events in window
    value: '0'
  - key: Events since startup
    value: '0'
  - key: Duration of window (s)
    value: '2.999869'
  - key: Actual frequency (Hz)
    value: '0.000000'
  - key: Target frequency (Hz)
    value: '0.000000'
  - key: Maximum acceptable frequency (Hz)
    value: '0.000000'
  - key: 'Earliest timestamp delay:'
    value: '0.000000'
  - key: 'Latest timestamp delay:'
    value: '0.000000'
  - key: 'Earliest acceptable timestamp delay:'
    value: '-1.000000'
  - key: 'Latest acceptable timestamp delay:'
    value: '5.000000'
  - key: 'Late diagnostic update count:'
    value: '0'
  - key: 'Early diagnostic update count:'
    value: '0'
  - key: 'Zero seen diagnostic update count:'
    value: '0'
---
header:
  stamp:
    sec: 1740806522
    nanosec: 52955374
  frame_id: ''
status:
- level: "\x02"
  name: 'oak: sys_logger'
  message: 'Communication exception - possible device error/misconfiguration. Original message ''Couldn''t read data from stream: ''sys_logger_...'
  hardware_id: oak_14442C103141E0D600_OAK-D-LITE
  values: []
---
header:
  stamp:
    sec: 1740806522
    nanosec: 556022533
  frame_id: ''
status:
- level: "\x02"
  name: 'rtabmap: Sync status'
  message: No events recorded.; No data since last update.
  hardware_id: none
  values:
  - key: Events in window
    value: '0'
  - key: Events since startup
    value: '0'
  - key: Duration of window (s)
    value: '4.999971'
  - key: Actual frequency (Hz)
    value: '0.000000'
  - key: Target frequency (Hz)
    value: '0.000000'
  - key: Maximum acceptable frequency (Hz)
    value: '0.000000'
  - key: 'Earliest timestamp delay:'
    value: '0.000000'
  - key: 'Latest timestamp delay:'
    value: '0.000000'
  - key: 'Earliest acceptable timestamp delay:'
    value: '-1.000000'
  - key: 'Latest acceptable timestamp delay:'
    value: '5.000000'
  - key: 'Late diagnostic update count:'
    value: '0'
  - key: 'Early diagnostic update count:'
    value: '0'
  - key: 'Zero seen diagnostic update count:'
    value: '0'
---
header:
  stamp:
    sec: 1740806522
    nanosec: 643193338
  frame_id: ''
status:
- level: "\x02"
  name: 'rtabmap_viz: Sync status'
  message: No events recorded.; No data since last update.
  hardware_id: none
  values:
  - key: Events in window
    value: '0'
  - key: Events since startup
    value: '0'
  - key: Duration of window (s)
    value: '3.999932'
  - key: Actual frequency (Hz)
    value: '0.000000'
  - key: Target frequency (Hz)
    value: '0.000000'
  - key: Maximum acceptable frequency (Hz)
    value: '0.000000'
  - key: 'Earliest timestamp delay:'
    value: '0.000000'
  - key: 'Latest timestamp delay:'
    value: '0.000000'
  - key: 'Earliest acceptable timestamp delay:'
    value: '-1.000000'
  - key: 'Latest acceptable timestamp delay:'
    value: '5.000000'
  - key: 'Late diagnostic update count:'
    value: '0'
  - key: 'Early diagnostic update count:'
    value: '0'
  - key: 'Zero seen diagnostic update count:'
    value: '0'
---
header:
  stamp:
    sec: 1740806523
    nanosec: 52457378
  frame_id: ''
status:
- level: "\x02"
  name: 'oak: sys_logger'
  message: 'Communication exception - possible device error/misconfiguration. Original message ''Couldn''t read data from stream: ''sys_logger_...'
  hardware_id: oak_14442C103141E0D600_OAK-D-LITE
  values: []
---
header:
  stamp:
    sec: 1740806523
    nanosec: 556030103
  frame_id: ''
status:
- level: "\x02"
  name: 'rtabmap: Sync status'
  message: No events recorded.; No data since last update.
  hardware_id: none
  values:
  - key: Events in window
    value: '0'
  - key: Events since startup
    value: '0'
  - key: Duration of window (s)
    value: '5.000002'
  - key: Actual frequency (Hz)
    value: '0.000000'
  - key: Target frequency (Hz)
    value: '0.000000'
  - key: Maximum acceptable frequency (Hz)
    value: '0.000000'
  - key: 'Earliest timestamp delay:'
    value: '0.000000'
  - key: 'Latest timestamp delay:'
    value: '0.000000'
  - key: 'Earliest acceptable timestamp delay:'
    value: '-1.000000'
  - key: 'Latest acceptable timestamp delay:'
    value: '5.000000'
  - key: 'Late diagnostic update count:'
    value: '0'
  - key: 'Early diagnostic update count:'
    value: '0'
  - key: 'Zero seen diagnostic update count:'
    value: '0'
---
header:
  stamp:
    sec: 1740806523
    nanosec: 643059316
  frame_id: ''
status:
- level: "\x02"
  name: 'rtabmap_viz: Sync status'
  message: No events recorded.; No data since last update.
  hardware_id: none
  values:
  - key: Events in window
    value: '0'
  - key: Events since startup
    value: '0'
  - key: Duration of window (s)
    value: '4.998765'
  - key: Actual frequency (Hz)
    value: '0.000000'
  - key: Target frequency (Hz)
    value: '0.000000'
  - key: Maximum acceptable frequency (Hz)
    value: '0.000000'
  - key: 'Earliest timestamp delay:'
    value: '0.000000'
  - key: 'Latest timestamp delay:'
    value: '0.000000'
  - key: 'Earliest acceptable timestamp delay:'
    value: '-1.000000'
  - key: 'Latest acceptable timestamp delay:'
    value: '5.000000'
  - key: 'Late diagnostic update count:'
    value: '0'
  - key: 'Early diagnostic update count:'
    value: '0'
  - key: 'Zero seen diagnostic update count:'
    value: '0'
---
header:
  stamp:
    sec: 1740806524
    nanosec: 52341937
  frame_id: ''
status:
- level: "\x02"
  name: 'oak: sys_logger'
  message: 'Communication exception - possible device error/misconfiguration. Original message ''Couldn''t read data from stream: ''sys_logger_...'
  hardware_id: oak_14442C103141E0D600_OAK-D-LITE
  values: []
---
header:
  stamp:
    sec: 1740806524
    nanosec: 555944614
  frame_id: ''
status:
- level: "\x02"
  name: 'rtabmap: Sync status'
  message: No events recorded.; No data since last update.
  hardware_id: none
  values:
  - key: Events in window
    value: '0'
  - key: Events since startup
    value: '0'
  - key: Duration of window (s)
    value: '4.999944'
  - key: Actual frequency (Hz)
    value: '0.000000'
  - key: Target frequency (Hz)
    value: '0.000000'
  - key: Maximum acceptable frequency (Hz)
    value: '0.000000'
  - key: 'Earliest timestamp delay:'
    value: '0.000000'
  - key: 'Latest timestamp delay:'
    value: '0.000000'
  - key: 'Earliest acceptable timestamp delay:'
    value: '-1.000000'
  - key: 'Latest acceptable timestamp delay:'
    value: '5.000000'
  - key: 'Late diagnostic update count:'
    value: '0'
  - key: 'Early diagnostic update count:'
    value: '0'
  - key: 'Zero seen diagnostic update count:'
    value: '0'
---
```
I couldn't find anything in the debug logs as well.

How does this work on the rovers that you guys test at the Waveshare factory?

Also, they've mentioned to set a parameter to camera_i_restart_on_diagnostics_error: true. How do I set that?

**Comment by naman-gupta99** [comment]
@DUDULRX Can you please help with this?

**Comment by naman-gupta99** [comment]
@DUDULRX @EffectsMachine Can you please help?

**Comment by DUDULRX** [comment]
modified this file“ugv_ws/src/ugv_main/ugv_vision/config/oak_d_lite.yaml”，

![Image](https://github.com/user-attachments/assets/931b377c-ab93-4f49-a869-614bd8b2502e)

`
      i_restart_on_diagnostics_error: true
`
 in ugv_ws folder   `colcon build --symlink-install --packages-select ugv_vision`

**Comment by naman-gupta99** [comment]
@DUDULRX This does restart the camera but the issue is still the same. LiDAR starts timing out.

![Image](https://github.com/user-attachments/assets/92bf853c-2b3b-4cd1-8861-076554ba0fa2)

**Comment by DUDULRX** [comment]
Your radar device may be connected or not working properly

**Comment by naman-gupta99** [comment]
@DUDULRX Please take a look at the logs. Whenever the RGB-D camera throws an error that's when the Lidar starts timing out. 
It cannot be that the Lidar is not connected or not working.
Can you please find a solution for the RGB-D Camera's issue?

**Comment by DUDULRX** [comment]
Or your device may be running out of power

**Comment by DUDULRX** [comment]
You can try charging it and testing it at the same time

**Comment by naman-gupta99** [comment]
Hello @DUDULRX .

I tried that but it still crashed within a few seconds.

**Comment by naman-gupta99** [comment]
@DUDULRX Do you have any other solution?

**Comment by DUDULRX** [comment]
You try using the python api of the oak camera to use the camera and see if it works
[[depthai-python](https://github.com/luxonis/depthai-python)](https://github.com/luxonis/depthai-python.git)

**Comment by naman-gupta99** [comment]
Hello @DUDULRX 
Sorry for the delayed response.
The luxonis team mentioned this in their issue.
> Thanks for the report, it looks like the device is running fine but it seems that there is some issue related to diagnostics which could be firmware related. Could you disable diagnostics? You can do that by setting pipeline_gen.i_enable_diagnostics: false parameter

I did the following change in the "ugv_ws/src/ugv_main/ugv_vision/config/oak_d_lite.yaml" file:
```
/oak:
  ros__parameters:
    camera:
      i_enable_imu: false
      i_enable_ir: false
      i_nn_type: none
      i_enable_diagnostics: false
    stereo:
      i_subpixel: true
```
Is this correct or should this go somewhere else?
